# Generated by Django 5.1 on 2024-08-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id_pesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_pesanan', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pajak', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nama_item', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.CharField(blank=True, max_length=255, null=True)),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='PesananItem',
            fields=[
                ('id_pesanan_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('harga_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.item')),
                ('id_pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.pesanan')),
            ],
        ),
    ]
