# Generated by Django 5.1 on 2024-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesanan',
            old_name='sub_total',
            new_name='nominal_bayar',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='pajak',
        ),
        migrations.AddField(
            model_name='pesanan',
            name='kembalian',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
