# Generated by Django 5.1 on 2024-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_rename_sub_total_pesanan_nominal_bayar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='kembalian',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='nominal_bayar',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
